return {
	-- {
	-- 	"rachartier/tiny-inline-diagnostic.nvim",
	-- 	event = "VeryLazy",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("tiny-inline-diagnostic").setup({
	-- 			options = {
	-- 				add_messages = {
	-- 					display_count = true,
	-- 				},
	-- 				multilines = {
	-- 					enabled = true,
	-- 					always_show = true,
	-- 					severity = { vim.diagnostics.severity.ERROR }
	-- 				},
	-- 				softwrap = 10
	-- 			}
	-- 		})
	-- 		-- vim.diagnostics.config({ virtual_text = false })
	-- 	end
	-- },
}
